### ISSUE TITLE
Populate a mongo store with fixtures

### ISSUE THREAD

**Issue by jonblack** [holidayextras/jsonapi-store-mongodb#13]
I'm trying to populate a mongo store with fixtures. I noticed that the `populate` function will load examples defined in the config, but it doesn't seem to get called. Am I supposed to call this myself? When is the best moment to do this?

**Comment by pmcnr-hx** [comment]
Hi @jonblack: you'll have to call `populate` explicitly somewhere, yes, since it is not something you'll want in a production implementation of the server. Let me know if you have trouble with this.

**Comment by jonblack** [comment]
I'm calling it after the `jsonApi.start()` function, but get an error that `self._db` is undefined so `dropDatabase` can't be called. I know why this is: the mongoHandler hasn't finished being created, it's still connecting. The trouble is, I don't see a way to get notification that the connection to mongo has completed.

**Comment by pmcnr-hx** [comment]
You'll probably have to wait for a bit for the MongoDB store to finish initialising before you call `populate`. That's currently a design decision, because the store initialisation is called done by the server. Notice how we wait before we populate in our tests: https://github.com/holidayextras/jsonapi-store-mongodb/blob/master/test/proxy.js#L28. Hope that helps!

**Comment by jonblack** [comment]
Excellent. Using a timeout as in the example worked. Thanks.
